### ISSUE TITLE
Block the address for other withdrawals

### ISSUE THREAD

**Issue by no8ody** [TangleBay/node-donation-handler#1]
If a donation is incoming, the funds must be blocked so that it is not used for a previous or subsequent donation payout, only for those for which it was originally intended.

Currently the payout also uses the other addresses, which is why the error "Not enough iotas found for payout" occurs.

**Comment by Thoralf-M** [comment]
https://github.com/TangleBay/node-donation-handler/commit/c18c7f842caa6cacb64840c98432a1ae6b1f091a

**Comment by Thoralf-M** [comment]
Payment module needs to be updated first
